-- AM-03 — assignment and returns.
--
-- Generated by Prisma, then HAND-EDITED to add the two constraints below.
-- Prisma's schema language expresses neither a partial unique index nor a
-- CHECK, so if this migration is ever regenerated, PRESERVE the hand-written
-- block at the bottom (same rule as the am02_asset_lifecycle tag CHECK).

-- AlterTable
--
-- AssetEvent.assignmentId exists to keep PERSONAL DATA OUT of this append-only
-- table: without it, "who held this asset" could only be recorded as free text
-- in `notes` — a copy of a person's name in a table that is never updated and
-- never deleted, where a name change or a DPA erasure request is unhonourable
-- by construction. The FK keeps exactly one copy of the person reference (on
-- Assignment) and the history renders by join.
ALTER TABLE "AssetEvent" ADD COLUMN     "assignmentId" TEXT;

-- CreateIndex
--
-- The per-person view ("everything X currently holds") and AM-07's search both
-- filter on exactly this pair.
CREATE INDEX "Assignment_personId_returnedAt_idx" ON "Assignment"("personId", "returnedAt");

-- AddForeignKey
--
-- RESTRICT, matching AssetEvent.actorId: nothing may silently blank audit
-- attribution. Assignment rows are never deleted anyway.
ALTER TABLE "AssetEvent" ADD CONSTRAINT "AssetEvent_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "Assignment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- HAND-WRITTEN BLOCK — preserve if this migration is ever regenerated.
-- ---------------------------------------------------------------------------

-- AC-1: "an asset cannot be assigned to two people at once (database
-- constraint)". This index IS that constraint — the application guard exists
-- for the error message, but this is the enforcement.
--
-- The WHERE clause is load-bearing and must never be dropped to "simplify"
-- this into a plain UNIQUE("assetId"). A total unique index would give each
-- asset at most one assignment EVER, making every asset permanently
-- unassignable after its first return — while still passing a naive
-- "can't assign twice" test. The integration suite pins this with a
-- falsifiability twin: after a return, a second assignment must succeed.
CREATE UNIQUE INDEX "Assignment_one_open_per_asset"
  ON "Assignment"("assetId") WHERE "returnedAt" IS NULL;

-- A return cannot predate its own checkout. Cheap here, and it stops AM-04's
-- imported assignment dates from landing inverted and silently corrupting the
-- custody timeline. NULL returnedAt (still held) is exempt.
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_returned_after_checkout"
  CHECK ("returnedAt" IS NULL OR "returnedAt" >= "checkedOutAt");

-- NOT enforceable in SQL, and deliberately not attempted: the coupling between
-- Asset.status = 'ASSIGNED' and the existence of an open Assignment. A CHECK
-- cannot reference another table. That coupling is a TRANSACTIONAL invariant
-- maintained by src/lib/asset-admin.ts, and the open Assignment row — not
-- Asset.status — is the source of truth for holdership. A reconciliation query
-- (README runbook) is the detection mechanism, not a constraint.
